# Configurations
title:            Game Hacking Academy
longtitle:        Game Hacking Academy
author:           attilathedud
email:            attilathedud@gmail.com
description: >
  Game hacking tutorials and lessons.

version:          1.0
gitbook_version:  3.2.3

url:              'https://gamehacking.academy'
baseurl:          ''
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: base16

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

tracker:
  google_analytics: "UA-160704775-1"

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
